import type { Metadata } from "next";
import { Content, Inter } from "next/font/google";
import "./globals.css";
import Navbar  from "./components/navbar/Navbar";
import Modal from "./components/modals/Modal";
import LoginModal from "./components/modals/app/components/LoginModal";


const inter = Inter({subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DjangoBnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (
    <p>yo yo</p>
  )


  return (
    <html lang="en">
      <body
        className={inter.className}>
          <Navbar/>

          <div className="pt-32">
          {children}
          </div>

          <LoginModal/>
          </body>
    </html>
  );
}
